### ISSUE TITLE
cannot open dub project

### ISSUE THREAD

**Issue by Extrawurst** [aBothe/Mono-D#643]
i guess it is related to https://github.com/aBothe/Mono-D/issues/639

loading `https://github.com/Extrawurst/unecht/blob/master/samples/helloworld/dub.json` is not possible:
<img width="598" alt="screen shot 2016-02-11 at 00 43 33" src="https://cloud.githubusercontent.com/assets/776816/12965737/c60afbaa-d058-11e5-9ebd-3b061600cbaa.png">

**Comment by Trollgeir** [comment]
I'm having the same problem with half of all my dub projects. Sometimes it works to temporary erase the dependencies from the dub file to load the project, and then fill them in again before trying to compile.

**Comment by Extrawurst** [comment]
"I think Xamarin tries to check every dependency while dub only loads once" - please elobarate, i dont understand that

**Comment by Trollgeir** [comment]
Sorry, sleepless night!

What I meant to say is that, if you load your main package which branches to other sub-packages, and if the sub-packages share some dependencies which you already loaded in the main package, those won't be checked by dub, but it might be checked by Xamarin. My problem was that the sub-packages (also dub files) had deprecated dependencies listed from the dub repository, but I think dub ignored them because they were already loaded by the main package (which had a path to the packages on my physical harddrive).

**Comment by Extrawurst** [comment]
unfortunately that is not the case in this project

**Comment by Trollgeir** [comment]
Have you tried to temporarily remove the dependencies in your main and/or sub-packages in a step-by-step fashion? This is how I was able to locate the source of the problem. Xamarin is able to load some dub files even if they don't compile.
